version: 2

models:
  - name: dim_employer
    schema: DWH
    description: "A test for dim employer"
    columns:
      - name: EMPLOYER_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_assessment_event_status
    schema: DWH
    description: "A test for dim assessment event status"
    columns:
      - name: ASSESSMENT_EVENT_STATUS_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_assessment_event_type
    schema: DWH
    description: "A test for dim assessment event type"
    columns:
      - name: ASSESSMENT_EVENT_TYPE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_grade
    schema: DWH
    description: "A test for dim grade"
    columns:
      - name: GRADE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_institution
    schema: DWH
    description: "A test for dim institution"
    columns:
      - name: INSTITUTION_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_member
    schema: DWH
    description: "A test for dim member"
    columns:
      - name: MEMBER_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_membership_status
    schema: DWH
    description: "A test for dim membership status"
    columns:
      - name: MEMBERSHIP_STATUS_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_membership_type
    schema: DWH
    description: "A test for dim membership type"
    columns:
      - name: MEMBERSHIP_TYPE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_qualification
    schema: DWH
    description: "A test for dim qualification"
    columns:
      - name: QUALIFICATION_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: dim_schedule_type
    schema: DWH
    description: "A test for dim schedule type"
    columns:
      - name: SCHEDULE_TYPE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_subject
    schema: DWH
    description: "A test for dim subject"
    columns:
      - name: SUBJECT_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_venue
    schema: DWH
    description: "A test for dim venue"
    columns:
      - name: VENUE_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fact_assessment_history
    schema: DWH
    description: "A test for fact assessment history"
    columns:
      - name: MEMBER_KEY
        description: "The primary key for this table"
        tests:
          - relationships:
              to: ref('dim_member')
              field: MEMBER_KEY

  - name: fact_employment_history
    schema: DWH
    description: "A test for fact employment history"
    columns:
      - name: MEMBER_KEY
        description: "The primary key for this table"
        tests:
          - relationships:
              to: ref('dim_member')
              field: MEMBER_KEY

  - name: fact_membership_history
    schema: DWH
    description: "A test for fact membership history"
    columns:
      - name: MEMBER_KEY
        description: "The primary key for this table"
        tests:
          - relationships:
              to: ref('dim_member')
              field: MEMBER_KEY

  - name: fact_qualification_history
    schema: DWH
    description: "A test for fact assessment history"
    columns:
      - name: MEMBER_KEY
        description: "The primary key for this table"
        tests:
          - relationships:
              to: ref('dim_member')
              field: MEMBER_KEY
        
  - name: fact_member_montly_snapshot
    schema: DWH
    description: "A test for fact assessment history"
    columns:
      - name: MEMBER_KEY
        description: "The primary key for this table"
        tests:
          - relationships:
              to: ref('dim_member')
              field: MEMBER_KEY
          





