
version: 2

models:
    - name: dim_employer
      description: "A starter dbt model"
      columns:
          - name: employer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

